import type { MicrophonePermissionSettings } from '@shared/app/app-permissions';
export declare function stopStream(stream: MediaStream | null): void;
export declare function canCaptureAudio(): boolean;
export declare function getAppMicrophoneEnabled(): Promise<boolean>;
export declare function dictationErrorMessage(error: unknown): string;
export declare function mergeDictationText(baseText: string, transcript: string): string;
export declare function preferredLanguage(): string | undefined;
export declare function resampleToPcm16(input: Float32Array, inputRate: number, outputRate: number): Int16Array;
export declare function pcm16ToBase64(pcm: Int16Array): string;
export declare function canRecordAudio(): boolean;
export declare function supportedMimeType(): string | undefined;
export declare function extensionForMimeType(mimeType: string): string;
export declare function createRecordingId(): string;
export declare function createRecordingFileName(mimeType: string): string;
export declare function normalizePermissionState(state: PermissionState): 'granted' | 'denied' | 'prompt' | 'unknown';
export declare function queryMicrophonePermission(): Promise<'granted' | 'denied' | 'prompt' | 'unknown'>;
export declare function getAppMicrophonePermission(): Promise<MicrophonePermissionSettings | null>;
export declare function recorderErrorMessage(error: unknown): string;
export declare function objectUrlForBlob(blob: Blob): string | undefined;
