import { type ChannelType } from './definitions';
export declare const CHANNEL_RUNTIME_SUPPORT_VALUES: readonly ["bundled", "catalog-only"];
export declare const CHANNEL_CATALOG_EXPOSURES: readonly ["stable", "preview", "hidden"];
export declare const CHANNEL_SETUP_FIELDS: readonly ["enabled", "token", "secret", "serverUrl", "webhookUrl", "appId", "clientId", "clientSecret", "username", "phoneNumber", "botUserId", "allowFrom", "groupAllowFrom", "defaultTarget", "dmPolicy", "heartbeat"];
export type ChannelRuntimeSupport = (typeof CHANNEL_RUNTIME_SUPPORT_VALUES)[number];
export type ChannelCatalogExposure = (typeof CHANNEL_CATALOG_EXPOSURES)[number];
export type ChannelSetupField = (typeof CHANNEL_SETUP_FIELDS)[number];
export interface ChannelCatalogEntry {
    id: ChannelType;
    label: string;
    blurb: string;
    docsPath: string;
    docsLabel: string;
    brandIconId?: string;
    aliases: readonly string[];
    order: number;
    markdownCapable: boolean;
    exposure: ChannelCatalogExposure;
    runtime: ChannelRuntimeSupport;
    setupVisible: boolean;
    catalogVisible: boolean;
    setupFields: readonly ChannelSetupField[];
    cliHints: readonly string[];
    setupHints: readonly string[];
}
export declare const CHANNEL_CATALOG: readonly ChannelCatalogEntry[];
export declare const CHANNEL_CATALOG_BY_ID: Readonly<Record<"line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser", ChannelCatalogEntry>>;
export declare const CHANNEL_ALIASES_BY_ID: Readonly<Record<"line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser", readonly string[]>>;
export declare const CHANNEL_DOCS_PATH_BY_ID: Readonly<Record<"line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser", string>>;
export declare const CHANNEL_RUNTIME_BY_ID: Readonly<Record<"line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser", "bundled" | "catalog-only">>;
export declare const CHANNEL_SETUP_FIELDS_BY_ID: Readonly<Record<"line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser", readonly ("username" | "enabled" | "token" | "allowFrom" | "phoneNumber" | "secret" | "serverUrl" | "webhookUrl" | "appId" | "clientId" | "clientSecret" | "botUserId" | "groupAllowFrom" | "defaultTarget" | "dmPolicy" | "heartbeat")[]>>;
export declare const CHANNEL_BUNDLED_RUNTIME_IDS: readonly ("line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser")[];
export declare const CHANNEL_CATALOG_ONLY_RUNTIME_IDS: readonly ("line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser")[];
export declare const CHANNEL_VISIBLE_CATALOG_IDS: readonly ("line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser")[];
export declare const CHANNEL_HIDDEN_CATALOG_IDS: readonly ("line" | "clickclack" | "discord" | "feishu" | "googlechat" | "imessage" | "irc" | "matrix" | "mattermost" | "msteams" | "nextcloud-talk" | "nostr" | "qa-channel" | "qqbot" | "signal" | "slack" | "synology-chat" | "telegram" | "tlon" | "twitch" | "whatsapp" | "zalo" | "zalouser")[];
export declare function listChannelCatalog(): readonly ChannelCatalogEntry[];
export declare function getChannelCatalogEntry(idOrAlias: string): ChannelCatalogEntry | undefined;
export declare function getChannelBrandIconId(idOrAlias: string): string | undefined;
export declare function buildChannelDocsUrl(docsPath: string, repositoryHomepage: string): string | null;
export declare function normalizeChannelId(idOrAlias: string): ChannelType | null;
export declare function isChannelId(value: string): value is ChannelType;
export declare function extractChannelCatalogFromPackageMetadata(metadata: unknown): readonly ChannelCatalogEntry[];
