export const TELEGRAM_MAX_MESSAGE_LENGTH = 4096;
export const TELEGRAM_HEALTH_CHECK_INTERVAL_MS = 60_000;
export const TELEGRAM_RECONNECT_INITIAL_DELAY_MS = 2_000;
export const TELEGRAM_RECONNECT_MAX_DELAY_MS = 60_000;
