export type {
	JsonObject,
	JsonValue,
	Task,
	TaskArtifactReference,
	TaskAttempt,
	TaskAuditLogEntry,
	TaskCancellationMode,
	TaskCleanupPolicy,
	TaskClientApi,
	TaskConfirmation,
	TaskCreateRequest,
	TaskDefinition,
	TaskDependency,
	TaskDependencyType,
	TaskError,
	TaskEvent,
	TaskEventType,
	TaskExecutionContext,
	TaskExecutionResult,
	TaskExecutor,
	TaskId,
	TaskListFilter,
	TaskLogEntry,
	TaskManager,
	TaskPermissionLevel,
	TaskPriority,
	TaskProgress,
	TaskQueue,
	TaskQueueStats,
	TaskResult,
	TaskRetryPolicy,
	TaskSchedulePolicy,
	TaskSchema,
	TaskSource,
	TaskStatus,
	TaskStore,
	TaskSubscription,
	TaskType,
	TaskVisibility,
	TaskWorker,
	Workflow,
	WorkflowCreateRequest,
	WorkflowId,
	WorkflowListFilter,
} from '../../../shared/task';

export const DEFAULT_RETRY_POLICY = {
	maxAttempts: 1,
	initialDelayMs: 250,
	maxDelayMs: 5_000,
	backoffMultiplier: 2,
	jitter: true,
	retryableErrorCodes: ['TRANSIENT', 'TIMEOUT', 'LOCK_FAILED'],
	nonRetryableErrorCodes: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'CANCELLED'],
} satisfies import('../../../shared/task').TaskRetryPolicy;

export const EMPTY_PROGRESS = (now: string): import('../../../shared/task').TaskProgress => ({
	percentage: 0,
	indeterminate: false,
	updatedAt: now,
});
