import type { CronJobInfo, CronSchedule, CronScheduleStatus } from '../../../../../../shared/app/cron';
export declare function formatTimestamp(value: number | string | undefined): string;
export declare function formatDuration(ms: number): string;
export declare function formatSchedule(schedule: CronSchedule): string;
export declare function formatJobSchedule(job: CronJobInfo): string;
export declare function inputSummary(schedule: CronSchedule): string;
export declare function inputEntries(schedule: CronSchedule): readonly (readonly [string, string])[];
export declare function statusLabelKey(status: CronScheduleStatus): string;
export declare function statusVariant(status: CronScheduleStatus): 'outline' | 'secondary' | 'destructive';
export declare function isCronSchedule(value: unknown): value is CronSchedule;
export declare function sortSchedules(schedules: readonly CronSchedule[]): CronSchedule[];
export declare function sortJobs(jobs: readonly CronJobInfo[]): CronJobInfo[];
