import type { CronScheduleCreateRequest } from '../core/cron.types';
import { AGENT_TASK_TYPE } from '../../tasks';

export function createExampleCronDefinitions(timezone = 'UTC'): CronScheduleCreateRequest[] {
	return [
		{
			name: 'Daily maintenance',
			type: 'cron',
			source: 'maintenance',
			createdBy: 'system',
			visibility: 'system',
			timezone,
			cronExpression: '0 3 * * *',
			missedRunPolicy: 'runOnce',
			concurrencyPolicy: 'skipIfRunning',
			taskType: AGENT_TASK_TYPE,
			taskInput: {
				message: 'Run the daily maintenance check and summarize anything that needs attention.',
			},
			taskPriority: 'low',
			taskTags: ['maintenance'],
		},
		{
			name: 'Memory compaction',
			type: 'cron',
			source: 'system',
			createdBy: 'system',
			visibility: 'system',
			timezone,
			cronExpression: '0 2 * * *',
			missedRunPolicy: 'skip',
			concurrencyPolicy: 'skipIfRunning',
			taskType: AGENT_TASK_TYPE,
			taskInput: {
				message: 'Review memory health and summarize any compaction work that should be done.',
			},
			taskPriority: 'low',
			taskTags: ['memory'],
		},
		{
			name: 'Connector sync',
			type: 'interval',
			source: 'connector',
			sourceId: 'github',
			createdBy: 'github-connector',
			visibility: 'user',
			timezone,
			intervalMs: 30 * 60_000,
			missedRunPolicy: 'skip',
			concurrencyPolicy: 'skipIfRunning',
			taskType: AGENT_TASK_TYPE,
			taskInput: {
				message: 'Check GitHub connector sync status and summarize any user-visible issues.',
			},
			taskPriority: 'normal',
			taskTags: ['sync', 'github'],
			requiredPermissions: ['scheduleConnectorAccess', 'scheduleNetworkAccess'],
		},
		{
			name: 'Weekly AI summary',
			type: 'cron',
			source: 'agent',
			sourceId: 'summary-agent',
			createdBy: 'summary-agent',
			visibility: 'user',
			timezone,
			cronExpression: '0 17 * * 5',
			missedRunPolicy: 'runOnce',
			concurrencyPolicy: 'queueIfRunning',
			taskType: AGENT_TASK_TYPE,
			taskInput: { message: 'Generate the weekly summary.' },
			taskPriority: 'normal',
			taskTags: ['summary'],
			requiredPermissions: ['scheduleReadPrivateData'],
			requiresConfirmation: false,
		},
	];
}
