import type { CronScheduleCreateRequest } from '../core/cron.types';

export function createExampleCronDefinitions(timezone = 'UTC'): CronScheduleCreateRequest[] {
	return [
		{
			name: 'Daily maintenance',
			type: 'cron',
			source: 'maintenance',
			createdBy: 'system',
			visibility: 'system',
			timezone,
			cronExpression: '0 3 * * *',
			missedRunPolicy: 'runOnce',
			concurrencyPolicy: 'skipIfRunning',
			taskType: 'cron.maintenance',
			taskInput: { kind: 'daily' },
			taskPriority: 'low',
			taskTags: ['maintenance'],
		},
		{
			name: 'Memory compaction',
			type: 'cron',
			source: 'system',
			createdBy: 'system',
			visibility: 'system',
			timezone,
			cronExpression: '0 2 * * *',
			missedRunPolicy: 'skip',
			concurrencyPolicy: 'skipIfRunning',
			taskType: 'memory.compact',
			taskInput: { mode: 'background' },
			taskPriority: 'low',
			taskTags: ['memory'],
		},
		{
			name: 'Connector sync',
			type: 'interval',
			source: 'connector',
			sourceId: 'github',
			createdBy: 'github-connector',
			visibility: 'user',
			timezone,
			intervalMs: 30 * 60_000,
			missedRunPolicy: 'skip',
			concurrencyPolicy: 'skipIfRunning',
			taskType: 'connector.sync',
			taskInput: { connectorId: 'github' },
			taskPriority: 'normal',
			taskTags: ['sync', 'github'],
			requiredPermissions: ['scheduleConnectorAccess', 'scheduleNetworkAccess'],
		},
		{
			name: 'Weekly AI summary',
			type: 'cron',
			source: 'agent',
			sourceId: 'summary-agent',
			createdBy: 'summary-agent',
			visibility: 'user',
			timezone,
			cronExpression: '0 17 * * 5',
			missedRunPolicy: 'runOnce',
			concurrencyPolicy: 'queueIfRunning',
			taskType: 'ai.agent.run',
			taskInput: { prompt: 'Generate the weekly summary.' },
			taskPriority: 'normal',
			taskTags: ['summary'],
			requiredPermissions: ['scheduleReadPrivateData'],
			requiresConfirmation: false,
		},
	];
}
