export * from './providers';
import {
	MINI_SPEECH_TRANSCRIBER_MODEL_ID,
	SPEECH_TO_TEXT_MODELS_BY_PROVIDER,
	TEXT_TO_SPEECH_MODELS_BY_PROVIDER,
	TEXT_TO_VIDEO_MODELS_BY_PROVIDER,
	TEXT_TO_IMAGE_MODELS_BY_PROVIDER,
	TEXT_TO_AUDIO_MODELS_BY_PROVIDER,
} from './providers';

export const SPEECH_TO_TEXT_PROVIDER_MODELS = SPEECH_TO_TEXT_MODELS_BY_PROVIDER;
export const TEXT_TO_SPEECH_PROVIDER_MODELS = TEXT_TO_SPEECH_MODELS_BY_PROVIDER;
export const TEXT_TO_VIDEO_PROVIDER_MODELS = TEXT_TO_VIDEO_MODELS_BY_PROVIDER;
export const TEXT_TO_IMAGE_PROVIDER_MODELS = TEXT_TO_IMAGE_MODELS_BY_PROVIDER;
export const MUSIC_PROVIDER_MODELS_BY_PROVIDER = TEXT_TO_AUDIO_MODELS_BY_PROVIDER;
export const MUSIC_CREATOR_PROVIDER_MODELS_BY_PROVIDER = TEXT_TO_AUDIO_MODELS_BY_PROVIDER;
export { MINI_SPEECH_TRANSCRIBER_MODEL_ID };
export const REALTIME_SPEECH_TRANSCRIBER_MODEL_ID = MINI_SPEECH_TRANSCRIBER_MODEL_ID;
