import type { ConnectorConfigFile } from './integration';

export const connectorsConfig = [
	{
		id: 'gmail',
		provider: 'google',
		type: 'oauth',
		displayName: 'Gmail',
		description: 'Search, read, draft, and send Gmail messages.',
		enabled: true,
		auth: { kind: 'oauth', requiredScopes: ['gmail.readonly', 'gmail.compose', 'gmail.send'] },
		defaultScopes: ['gmail.readonly', 'gmail.compose', 'gmail.send'],
		allowedPermissions: ['readMetadata', 'readPrivate', 'writeDraft', 'writeExternal'],
		trustLevel: 'verifiedThirdParty',
		dataSensitivity: 'private',
		rateLimit: { perMinute: 60, budgetPerUser: 500 },
		toolAllowlist: ['search', 'read', 'draft', 'send'],
		metadata: { allowedWriteTools: ['draft'] },
	},
	{
		id: 'local_files_mcp',
		provider: 'local',
		type: 'mcp',
		displayName: 'Local Files MCP',
		description: 'Sandboxed local MCP server for file search and snippet reads.',
		enabled: false,
		auth: { kind: 'local', credentialRef: 'local-files-sandbox' },
		defaultScopes: ['files.read'],
		allowedPermissions: ['readMetadata', 'readPrivate'],
		trustLevel: 'userInstalled',
		dataSensitivity: 'private',
		transport: {
			transport: 'stdio',
			command: process.execPath,
			args: ['local-files-mcp'],
			env: { PATH: process.env.PATH ?? '' },
			sandbox: true,
		},
		timeoutMs: 10_000,
		retryPolicy: { retries: 1, backoffMs: 100 },
		rateLimit: { perMinute: 20, budgetPerSession: 100 },
		toolAllowlist: ['search', 'read'],
	},
] satisfies ConnectorConfigFile;
