export const HeartbeatChannels = {
    status: 'heartbeat:status',
    last: 'heartbeat:last',
    settings: 'heartbeat:settings',
    saveSettings: 'heartbeat:save-settings',
    setEnabled: 'heartbeat:set-enabled',
    getTiming: 'heartbeat:get-timing',
    updateTiming: 'heartbeat:update-timing',
    setProviderId: 'heartbeat:set-provider-id',
    setModelId: 'heartbeat:set-model-id',
    setReasoningEffort: 'heartbeat:set-reasoning-effort',
    systemEvent: 'heartbeat:system-event',
    request: 'heartbeat:request',
    event: 'heartbeat:event',
};
