import { AGENT_TOOL_APPROVAL_NONE } from './policy';
import type { AgentToolMetadata, AgentToolProfile } from './types';

const DEFAULT_TOOL_PROFILES = ['coding', 'standard', 'full'] as const satisfies readonly AgentToolProfile[];

export const AGENT_TOOLS = [
	{
		name: 'web.run',
		group: 'web',
		title: 'Web and live data access',
		description:
			'Accesses internet search, page reading, link navigation, page lookup, PDF screenshots, image search, finance, weather, sports, and time queries.',
		permissions: ['web', 'read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'image_gen.imagegen',
		group: 'image',
		title: 'Image generation and image editing',
		description:
			'Generates images from text prompts and edits uploaded images based on requested visual changes.',
		permissions: ['image', 'create', 'write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.exec_command',
		group: 'functions',
		title: 'Shell command execution',
		description: 'Runs a shell command and returns command output or a session id for ongoing interaction.',
		permissions: ['shell', 'read', 'write', 'execute'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.write_stdin',
		group: 'functions',
		title: 'Existing process input and polling',
		description: 'Writes text to a running exec_command session and returns recent output.',
		permissions: ['shell', 'read', 'write', 'execute'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.apply_patch',
		group: 'functions',
		title: 'Structured file patch editor',
		description: 'Applies a structured patch that adds, updates, moves, or deletes files.',
		permissions: ['filesystem', 'create', 'write', 'delete'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.view_image',
		group: 'functions',
		title: 'Local image viewer',
		description: 'Opens a local image file for visual inspection.',
		permissions: ['read', 'image'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.update_plan',
		group: 'functions',
		title: 'Task plan updater',
		description: 'Updates a visible task plan with step status and optional explanation.',
		permissions: ['state', 'write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.get_goal',
		group: 'functions',
		title: 'Goal status reader',
		description: 'Gets the current thread goal, status, budgets, usage, and remaining budget.',
		permissions: ['state', 'read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.create_goal',
		group: 'functions',
		title: 'Goal creator',
		description: 'Creates a new active thread goal only when explicitly requested and no goal already exists.',
		permissions: ['state', 'create'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.update_goal',
		group: 'functions',
		title: 'Goal status updater',
		description: 'Marks an existing goal as complete or blocked under strict rules.',
		permissions: ['state', 'write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.list_mcp_resources',
		group: 'mcp',
		title: 'MCP resource lister',
		description: 'Lists resources exposed by configured MCP servers.',
		permissions: ['mcp:read', 'read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.list_mcp_resource_templates',
		group: 'mcp',
		title: 'MCP resource template lister',
		description: 'Lists parameterized resource templates exposed by configured MCP servers.',
		permissions: ['mcp:read', 'read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.read_mcp_resource',
		group: 'mcp',
		title: 'MCP resource reader',
		description: 'Reads a specific MCP resource by server name and URI.',
		permissions: ['mcp:read', 'read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'functions.request_user_input',
		group: 'functions',
		title: 'Structured user input requester',
		description: 'Requests one to three short questions and waits for the user response.',
		permissions: ['human', 'write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'multi_tool_use.parallel',
		group: 'multiTool',
		title: 'Parallel developer-tool runner',
		description: 'Runs multiple developer tools simultaneously when the calls are independent.',
		permissions: ['execute', 'read', 'write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'tool_search.tool_search_tool',
		group: 'toolSearch',
		title: 'Deferred tool discovery',
		description: 'Searches deferred tool metadata and exposes matching tools for the next model step.',
		permissions: ['read', 'tool:discovery'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'multi_agent_v1.spawn_agent',
		group: 'multiAgent',
		title: 'Sub-agent spawner',
		description: 'Starts a delegated sub-agent for a well-scoped task.',
		permissions: ['delegate', 'create'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'multi_agent_v1.resume_agent',
		group: 'multiAgent',
		title: 'Closed sub-agent resumer',
		description: 'Resumes a previously closed agent by id so it can receive input or be waited on.',
		permissions: ['delegate', 'write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'multi_agent_v1.send_input',
		group: 'multiAgent',
		title: 'Sub-agent input sender',
		description: 'Sends a message or structured input items to an existing sub-agent.',
		permissions: ['delegate', 'write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'multi_agent_v1.wait_agent',
		group: 'multiAgent',
		title: 'Sub-agent waiter',
		description: 'Waits for one or more sub-agents to reach a final status.',
		permissions: ['delegate', 'read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'multi_agent_v1.close_agent',
		group: 'multiAgent',
		title: 'Sub-agent closer',
		description: 'Closes an agent and open descendants when they are no longer needed.',
		permissions: ['delegate', 'delete'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
] as const satisfies readonly AgentToolMetadata[];
