import { AGENT_TOOL_APPROVAL_ALWAYS, AGENT_TOOL_APPROVAL_NONE } from './policy';
import type { AgentToolMetadata, AgentToolProfile } from './types';

const DEFAULT_TOOL_PROFILES = ['coding', 'standard', 'full'] as const satisfies readonly AgentToolProfile[];
const OPTIONAL_TOOL_PROFILES = ['full'] as const satisfies readonly AgentToolProfile[];
export const AGENT_TOOLS = [
	{
		name: 'read',
		group: 'coreWorkspace',
		title: 'Read file',
		description: 'Read a UTF-8 workspace file with optional line offset and limit.',
		permissions: ['read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'edit',
		group: 'coreWorkspace',
		title: 'Edit file',
		description: 'Replace exact text in a UTF-8 workspace file.',
		permissions: ['write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'find',
		group: 'coreWorkspace',
		title: 'Search files',
		description: 'Find workspace paths by glob pattern.',
		permissions: ['read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'exec',
		group: 'coreWorkspace',
		title: 'Run shell',
		description:
			'Run a shell command in the workspace, optionally in the background, with output capped and a safety deny-list.',
		permissions: ['read', 'write', 'execute'],
		approval: AGENT_TOOL_APPROVAL_ALWAYS,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'write',
		group: 'coreWorkspace',
		title: 'Write file',
		description: 'Create or overwrite a UTF-8 workspace file.',
		permissions: ['create', 'write'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'write_todos',
		group: 'stateTask',
		title: 'Write todos',
		description: 'Replace the current run todo list.',
		permissions: ['state'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'update_todo',
		group: 'stateTask',
		title: 'Update todo',
		description: 'Update one item in the current run todo list.',
		permissions: ['state'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'list_todos',
		group: 'stateTask',
		title: 'List todos',
		description: 'List the current run todo items and statuses.',
		permissions: ['state'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'complete_task',
		group: 'stateTask',
		title: 'Complete task',
		description: 'Mark the current task or a todo item as complete.',
		permissions: ['state'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'write_scratch',
		group: 'stateTask',
		title: 'Write scratch',
		description: 'Write run-local scratch notes for later tool calls.',
		permissions: ['state'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'read_scratch',
		group: 'stateTask',
		title: 'Read scratch',
		description: 'Read run-local scratch notes.',
		permissions: ['state'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'skill_list',
		group: 'skill',
		title: 'Skill list',
		description: 'List installed skills available to the agent.',
		permissions: ['skill'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'skill_load',
		group: 'skill',
		title: 'Skill load',
		description: 'Load instructions and support file metadata for an installed skill.',
		permissions: ['skill'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'skill_use',
		group: 'skill',
		title: 'Skill use',
		description: 'Select and load a skill for the current task.',
		permissions: ['skill'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_list_servers',
		group: 'mcpConnector',
		title: 'List MCP servers',
		description: 'List configured MCP connector servers.',
		permissions: ['mcp:read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_connect_server',
		group: 'mcpConnector',
		title: 'Connect MCP server',
		description: 'Connect to or test a configured MCP server.',
		permissions: ['mcp:connect'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_refresh_server',
		group: 'mcpConnector',
		title: 'Refresh MCP server',
		description: 'Refresh a configured MCP server and its discovered capabilities.',
		permissions: ['mcp:connect'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_list_tools',
		group: 'mcpConnector',
		title: 'List MCP tools',
		description: 'List tools exposed by a configured MCP server.',
		permissions: ['mcp:read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_load_tool',
		group: 'mcpConnector',
		title: 'Load MCP tool',
		description: 'Load schema and metadata for one MCP tool.',
		permissions: ['mcp:read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_call_tool',
		group: 'mcpConnector',
		title: 'Call MCP tool',
		description: 'Call a tool on a configured MCP server.',
		permissions: ['mcp:call'],
		approval: AGENT_TOOL_APPROVAL_ALWAYS,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_list_resources',
		group: 'mcpConnector',
		title: 'List MCP resources',
		description: 'List resources exposed by a configured MCP server.',
		permissions: ['mcp:read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_read_resource',
		group: 'mcpConnector',
		title: 'Read MCP resource',
		description: 'Read a resource from a configured MCP server.',
		permissions: ['mcp:read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_list_prompts',
		group: 'mcpConnector',
		title: 'List MCP prompts',
		description: 'List prompts exposed by a configured MCP server.',
		permissions: ['mcp:read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'mcp_load_prompt',
		group: 'mcpConnector',
		title: 'Load MCP prompt',
		description: 'Load a prompt from a configured MCP server.',
		permissions: ['mcp:read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'web_fetch',
		group: 'web',
		title: 'Fetch web page',
		description: 'Fetch an HTTP or HTTPS URL and return readable text capped at 1 MB.',
		permissions: ['read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'open_browser',
		group: 'web',
		title: 'Open browser',
		description: "Open an HTTP or HTTPS URL in the user's default browser.",
		permissions: ['read'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: DEFAULT_TOOL_PROFILES,
		availability: 'default',
	},
	{
		name: 'cron_create',
		group: 'cron',
		title: 'Create cron schedule',
		description: 'Create a scheduled job through CronService.',
		permissions: ['cron:createSchedule'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: OPTIONAL_TOOL_PROFILES,
		availability: 'optional',
	},
	{
		name: 'cron_read',
		group: 'cron',
		title: 'Read cron schedule',
		description: 'Read a scheduled job through CronService.',
		permissions: ['cron:scheduleReadPrivateData'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: OPTIONAL_TOOL_PROFILES,
		availability: 'optional',
	},
	{
		name: 'cron_update',
		group: 'cron',
		title: 'Update cron schedule',
		description: 'Update a scheduled job through CronService.',
		permissions: ['cron:updateSchedule'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: OPTIONAL_TOOL_PROFILES,
		availability: 'optional',
	},
	{
		name: 'cron_delete',
		group: 'cron',
		title: 'Delete cron schedule',
		description: 'Delete a scheduled job through CronService.',
		permissions: ['cron:deleteSchedule'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: OPTIONAL_TOOL_PROFILES,
		availability: 'optional',
	},
	{
		name: 'cron_list',
		group: 'cron',
		title: 'List cron schedules',
		description: 'List scheduled jobs through CronService.',
		permissions: ['cron:listSchedules'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: OPTIONAL_TOOL_PROFILES,
		availability: 'optional',
	},
	{
		name: 'cron_start',
		group: 'cron',
		title: 'Start cron schedule',
		description: 'Start a paused scheduled job through CronService.',
		permissions: ['cron:resumeSchedule'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: OPTIONAL_TOOL_PROFILES,
		availability: 'optional',
	},
	{
		name: 'cron_stop',
		group: 'cron',
		title: 'Stop cron schedule',
		description: 'Stop a scheduled job through CronService.',
		permissions: ['cron:pauseSchedule'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: OPTIONAL_TOOL_PROFILES,
		availability: 'optional',
	},
	{
		name: 'cron_run',
		group: 'cron',
		title: 'Run cron schedule now',
		description: 'Run a scheduled job immediately through CronService.',
		permissions: ['cron:runScheduleNow'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: OPTIONAL_TOOL_PROFILES,
		availability: 'optional',
	},
	{
		name: 'file_delete',
		group: 'coreWorkspace',
		title: 'Delete file',
		description: 'Delete a file directly, or a directory when recursive deletion is requested.',
		permissions: ['delete'],
		approval: AGENT_TOOL_APPROVAL_NONE,
		profiles: LEGACY_TOOL_PROFILES,
		availability: 'default',
	},
] as const satisfies readonly AgentToolMetadata[];
