import { PROVIDER_CONNECTOR_DOCS } from './provider-docs';
import type {
	ConnectorAuthKind,
	DirectConnectorCatalogEntry,
	OpenAiConnectorCatalogEntry,
} from './types';

export const CONNECTOR_PRIORITY_TIERS = ['P0', 'P1', 'P2', 'P3'] as const;
export type ConnectorPriorityTier = (typeof CONNECTOR_PRIORITY_TIERS)[number];

export const CONNECTOR_WRITE_RISKS = ['low', 'medium', 'high', 'critical'] as const;
export type ConnectorWriteRisk = (typeof CONNECTOR_WRITE_RISKS)[number];

export const CONNECTOR_DOCUMENTATION_STATUSES = [
	'official_public_web_checked_2026-05-19',
	'official_public_url_not_reverified_in_this_run',
	'vendor_portal_or_customer_access_required',
	'general_product_or_documentation_page',
] as const;
export type ConnectorDocumentationStatus = (typeof CONNECTOR_DOCUMENTATION_STATUSES)[number];

export type ConnectorImplementationPattern =
	| 'direct_api_or_connector_provider_tool'
	| 'custom_mcp_or_tool_wrapper_over_openapi'
	| 'custom_mcp_or_tool_wrapper_over_graphql'
	| 'controlled_query_gateway_with_read_only_roles'
	| 'event_trigger_into_agent_or_workflow_orchestrator'
	| 'local_or_enterprise_file_mcp_server'
	| 'rpa_or_browser_agent_with_policy_guardrails'
	| 'sandboxed_command_tool_or_mcp_server';

export type ConnectorRecommendedInitialMode = 'read_only_then_draft_write_actions';

const DOC_STATUS = 'official_public_web_checked_2026-05-19';
const DOC_STATUS_UNVERIFIED = 'official_public_url_not_reverified_in_this_run';

export const DIRECT_CONNECTOR_CATALOG = [
	{
		id: 'gmail',
		name: 'Gmail',
		vendor: 'Google',
		category: 'productivity_email',
		priorityTier: 'P0',
		usefulnessScore0To100: 98,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Direct API for core email workflows; Composio/Pipedream/Zapier for simpler automations.',
		documentationPages: [
			{ label: 'Gmail API guides', url: 'https://developers.google.com/workspace/gmail/api/guides', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Gmail API reference', url: 'https://developers.google.com/workspace/gmail/api/reference/rest', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'domain-wide delegation/service account for Workspace admins'],
		coreAgentActions: ['read and search email', 'summarize threads', 'draft replies', 'send approved email', 'label and archive messages'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['send_email', 'delete_email', 'create_forwarding_rule', 'modify_security_sensitive_settings'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Email is high prompt-injection risk; treat message body as untrusted content.',
	},
	{
		id: 'google_drive',
		name: 'Google Drive',
		vendor: 'Google',
		category: 'file_storage',
		priorityTier: 'P0',
		usefulnessScore0To100: 97,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Google Drive API overview', url: 'https://developers.google.com/workspace/drive/api/guides/about-sdk', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
			{ label: 'Google Drive API reference', url: 'https://developers.google.com/drive/api/reference/rest/v3', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'service account/domain-wide delegation'],
		coreAgentActions: ['search files', 'retrieve documents', 'create folders', 'upload files', 'manage sharing after approval'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['change_sharing_permissions', 'delete_files', 'move_sensitive_files', 'publish_files'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use permission-aware retrieval; never bypass Drive ACLs.',
	},
	{
		id: 'google_docs',
		name: 'Google Docs',
		vendor: 'Google',
		category: 'documents',
		priorityTier: 'P0',
		usefulnessScore0To100: 94,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Google Docs API reference', url: 'https://developers.google.com/workspace/docs/api/reference/rest', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'service account/domain-wide delegation'],
		coreAgentActions: ['read documents', 'create drafts', 'insert text', 'summarize documents', 'apply approved edits'],
		writeRisk: 'medium',
		humanApprovalRequiredFor: ['overwrite_document', 'share_document_externally', 'delete_content'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Useful for report, policy, proposal, and meeting-note workflows.',
	},
	{
		id: 'google_sheets',
		name: 'Google Sheets',
		vendor: 'Google',
		category: 'spreadsheets',
		priorityTier: 'P0',
		usefulnessScore0To100: 95,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Google Sheets API reference', url: 'https://developers.google.com/workspace/sheets/api/reference/rest', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'service account/domain-wide delegation'],
		coreAgentActions: ['read sheets', 'append rows', 'update cells', 'create reports', 'generate formulas'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['write_financial_data', 'bulk_update_cells', 'delete_sheets', 'share_spreadsheet'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Validate formulas and ranges to avoid accidental overwrites.',
	},
	{
		id: 'google_calendar',
		name: 'Google Calendar',
		vendor: 'Google',
		category: 'calendar',
		priorityTier: 'P0',
		usefulnessScore0To100: 95,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Google Calendar API overview', url: 'https://developers.google.com/workspace/calendar/api/guides/overview', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Google Calendar API reference', url: 'https://developers.google.com/workspace/calendar/api/v3/reference', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'service account/domain-wide delegation'],
		coreAgentActions: ['read availability', 'schedule meetings', 'reschedule events', 'create reminders', 'summarize agenda'],
		writeRisk: 'medium',
		humanApprovalRequiredFor: ['invite_external_guests', 'cancel_events', 'modify_recurring_events'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'For scheduling agents, enforce attendee/timezone confirmation rules.',
	},
	{
		id: 'google_chat',
		name: 'Google Chat',
		vendor: 'Google',
		category: 'messaging',
		priorityTier: 'P1',
		usefulnessScore0To100: 82,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Google Chat API overview', url: 'https://developers.google.com/workspace/chat/api/guides/overview', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Google Chat API reference', url: 'https://developers.google.com/workspace/chat/api/reference/rest', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'service account', 'app authentication'],
		coreAgentActions: ['post messages', 'create spaces', 'summarize spaces', 'route approvals', 'notify users'],
		writeRisk: 'medium',
		humanApprovalRequiredFor: ['post_to_large_channel', 'create_external_space', 'delete_messages'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Best for Google Workspace-first organizations.',
	},
	{
		id: 'google_meet',
		name: 'Google Meet',
		vendor: 'Google',
		category: 'meetings',
		priorityTier: 'P1',
		usefulnessScore0To100: 84,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Google Meet API overview', url: 'https://developers.google.com/workspace/meet/api/guides/overview', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Google Meet API reference', url: 'https://developers.google.com/workspace/meet/api/reference/rest', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0'],
		coreAgentActions: ['create meeting spaces', 'retrieve conference records', 'summarize meeting metadata', 'link meetings to calendar events'],
		writeRisk: 'medium',
		humanApprovalRequiredFor: ['create_external_meeting', 'change_meeting_access'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Pair with Calendar and transcription/recording sources where permitted.',
	},
	{
		id: 'microsoft_graph',
		name: 'Microsoft Graph / Microsoft 365',
		vendor: 'Microsoft',
		category: 'productivity_suite',
		priorityTier: 'P0',
		usefulnessScore0To100: 98,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use Microsoft Graph directly for core enterprise workflows; optionally wrap selected operations as MCP tools.',
		documentationPages: [
			{ label: 'Microsoft Graph overview', url: 'https://learn.microsoft.com/en-us/graph/overview', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Use the Microsoft Graph API', url: 'https://learn.microsoft.com/en-us/graph/use-the-api', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'Microsoft Entra app registration', 'delegated permissions', 'application permissions'],
		coreAgentActions: ['access Microsoft 365 data', 'query users/groups', 'read files/mail/calendars', 'automate collaboration workflows'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['application_permission_access', 'send_mail', 'change_group_membership', 'share_files_externally'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Central API surface for Outlook, Teams, SharePoint, OneDrive, users, groups, and more.',
	},
	{
		id: 'outlook',
		name: 'Outlook Mail and Calendar',
		vendor: 'Microsoft',
		category: 'productivity_email_calendar',
		priorityTier: 'P0',
		usefulnessScore0To100: 96,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Outlook mail API overview', url: 'https://learn.microsoft.com/en-us/graph/outlook-mail-concept-overview', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
			{ label: 'Outlook calendar API overview', url: 'https://learn.microsoft.com/en-us/graph/outlook-calendar-concept-overview', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0 via Microsoft Graph', 'delegated/application permissions'],
		coreAgentActions: ['read mail', 'draft/send email', 'schedule meetings', 'summarize threads', 'manage calendar events'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['send_email', 'delete_email', 'cancel_events', 'invite_external_guests'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Treat inbox content as untrusted input and enforce scoped permissions.',
	},
	{
		id: 'microsoft_teams',
		name: 'Microsoft Teams',
		vendor: 'Microsoft',
		category: 'messaging_collaboration',
		priorityTier: 'P0',
		usefulnessScore0To100: 94,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Microsoft Teams Graph API overview', url: 'https://learn.microsoft.com/en-us/graph/teams-concept-overview', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Microsoft Teams API reference', url: 'https://learn.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0 via Microsoft Graph', 'delegated/application permissions'],
		coreAgentActions: ['summarize channels', 'send messages', 'create meetings', 'route approvals', 'retrieve team/channel context'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['post_to_broad_channel', 'create_team', 'change_membership', 'send_external_message'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Core communication connector for Microsoft-first companies.',
	},
	{
		id: 'sharepoint_onedrive',
		name: 'SharePoint and OneDrive',
		vendor: 'Microsoft',
		category: 'file_storage',
		priorityTier: 'P0',
		usefulnessScore0To100: 96,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'OneDrive/SharePoint files in Microsoft Graph', url: 'https://learn.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'SharePoint sites API', url: 'https://learn.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0 via Microsoft Graph', 'delegated/application permissions'],
		coreAgentActions: ['search files', 'retrieve content', 'summarize documents', 'create files', 'manage links after approval'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['share_externally', 'delete_files', 'change_site_permissions'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use ACL-preserving retrieval and sensitivity label awareness where available.',
	},
	{
		id: 'microsoft_excel',
		name: 'Microsoft Excel',
		vendor: 'Microsoft',
		category: 'spreadsheets',
		priorityTier: 'P1',
		usefulnessScore0To100: 90,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Excel in Microsoft Graph', url: 'https://learn.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0 via Microsoft Graph'],
		coreAgentActions: ['read workbooks', 'update ranges', 'create tables', 'generate reports', 'calculate workbook data'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['bulk_update_ranges', 'delete_worksheets', 'write_financial_data'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Useful for finance, operations, and reporting agents.',
	},
	{
		id: 'slack',
		name: 'Slack',
		vendor: 'Salesforce',
		category: 'messaging_collaboration',
		priorityTier: 'P0',
		usefulnessScore0To100: 97,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct Slack app for core assistant UX; use provider tooling for standard actions.',
		documentationPages: [
			{ label: 'Slack developer docs', url: 'https://docs.slack.dev/', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Slack agents', url: 'https://docs.slack.dev/ai/agents', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'Slack app tokens', 'bot/user tokens'],
		coreAgentActions: ['read channel context', 'summarize conversations', 'post messages', 'create workflow notifications', 'collect approvals'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['post_to_broad_channel', 'invite_external_users', 'delete_messages', 'read_private_channels'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Limit long-term retention/indexing and preserve workspace permissions.',
	},
	{
		id: 'github',
		name: 'GitHub',
		vendor: 'GitHub/Microsoft',
		category: 'source_control_engineering',
		priorityTier: 'P0',
		usefulnessScore0To100: 98,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use GitHub App/direct API for production coding agents; expose tightly scoped MCP tools.',
		documentationPages: [
			{ label: 'GitHub REST API', url: 'https://docs.github.com/en/rest', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'GitHub Pull Requests REST API', url: 'https://docs.github.com/en/rest/pulls', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth app', 'GitHub App', 'fine-grained personal access token'],
		coreAgentActions: ['search repositories', 'read code', 'open issues', 'review pull requests', 'create branches', 'trigger workflows'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['push_code', 'merge_pull_request', 'delete_branch', 'modify_workflows', 'change_repo_permissions'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use least-privilege repo scopes and never allow autonomous merges without policy gates.',
	},
	{
		id: 'jira',
		name: 'Jira Cloud',
		vendor: 'Atlassian',
		category: 'project_management',
		priorityTier: 'P0',
		usefulnessScore0To100: 95,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Jira Cloud REST API v3', url: 'https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'API token', 'Atlassian Forge/Connect app'],
		coreAgentActions: ['create issues', 'update tickets', 'summarize sprint status', 'link blockers', 'triage backlog'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['bulk_update_issues', 'delete_issues', 'change_project_permissions', 'transition_critical_work_items'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Key connector for engineering/product agents.',
	},
	{
		id: 'confluence',
		name: 'Confluence Cloud',
		vendor: 'Atlassian',
		category: 'knowledge_base',
		priorityTier: 'P0',
		usefulnessScore0To100: 92,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Confluence Cloud REST API', url: 'https://developer.atlassian.com/cloud/confluence/rest/', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'API token', 'Atlassian Forge/Connect app'],
		coreAgentActions: ['search pages', 'summarize docs', 'create pages', 'update runbooks', 'link Jira issues'],
		writeRisk: 'medium',
		humanApprovalRequiredFor: ['publish_policy_pages', 'delete_pages', 'change_page_restrictions'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use page-level permission checks in RAG and editing flows.',
	},
	{
		id: 'notion',
		name: 'Notion',
		vendor: 'Notion',
		category: 'knowledge_base_database',
		priorityTier: 'P0',
		usefulnessScore0To100: 93,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Notion API overview', url: 'https://developers.notion.com/reference/intro', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Notion database API', url: 'https://developers.notion.com/reference/database', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'internal integration token'],
		coreAgentActions: ['search pages', 'read databases', 'create pages', 'update databases', 'summarize workspaces'],
		writeRisk: 'medium',
		humanApprovalRequiredFor: ['modify_shared_pages', 'delete_content', 'publish_sensitive_pages'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Strong knowledge/database connector for startups and product teams.',
	},
	{
		id: 'salesforce',
		name: 'Salesforce',
		vendor: 'Salesforce',
		category: 'crm_revenue',
		priorityTier: 'P0',
		usefulnessScore0To100: 97,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Direct API for revenue-critical production workflows; provider platform for lower-risk actions.',
		documentationPages: [
			{ label: 'Salesforce API library', url: 'https://developer.salesforce.com/docs/apis', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Salesforce REST API', url: 'https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'connected app', 'JWT bearer flow'],
		coreAgentActions: ['read accounts/opportunities', 'summarize pipeline', 'update records', 'create tasks', 'draft follow-ups'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['update_revenue_records', 'delete_records', 'change_ownership', 'mass_update_records'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Apply field-level security, record visibility, and audit logging.',
	},
	{
		id: 'hubspot',
		name: 'HubSpot',
		vendor: 'HubSpot',
		category: 'crm_marketing_sales',
		priorityTier: 'P0',
		usefulnessScore0To100: 92,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'HubSpot API reference', url: 'https://developers.hubspot.com/docs/api-reference/overview', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'HubSpot CRM guide', url: 'https://developers.hubspot.com/docs/guides/crm/overview', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'private app access token'],
		coreAgentActions: ['read contacts/companies/deals', 'create CRM notes', 'update lifecycle stages', 'draft sales emails', 'summarize pipeline'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['bulk_update_contacts', 'send_sales_email', 'delete_records', 'change_deal_stage'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Good all-in-one CRM/marketing connector for SMB/mid-market.',
	},
	{
		id: 'zendesk',
		name: 'Zendesk',
		vendor: 'Zendesk',
		category: 'customer_support',
		priorityTier: 'P0',
		usefulnessScore0To100: 92,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Zendesk API reference', url: 'https://developer.zendesk.com/api-reference/', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Zendesk Tickets API', url: 'https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'API token', 'basic auth'],
		coreAgentActions: ['read tickets', 'triage requests', 'draft replies', 'update status', 'summarize customer history'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['send_customer_reply', 'close_ticket', 'delete_ticket', 'change_user_data'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use draft-and-approve mode for customer-facing messages.',
	},
	{
		id: 'servicenow',
		name: 'ServiceNow',
		vendor: 'ServiceNow',
		category: 'itsm_enterprise_workflows',
		priorityTier: 'P0',
		usefulnessScore0To100: 90,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'ServiceNow REST APIs', url: 'https://developer.servicenow.com/dev.do#!/reference/api/utah/rest/c_TableAPI', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'ServiceNow REST API docs', url: 'https://www.servicenow.com/docs/bundle/xanadu-api-reference/page/integrate/inbound-rest/concept/c_RESTAPI.html', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['Basic auth', 'OAuth 2.0', 'mutual TLS/enterprise SSO options'],
		coreAgentActions: ['read incidents', 'create/change tickets', 'summarize incidents', 'route approvals', 'update CMDB records'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['close_incident', 'change_cmdb', 'approve_change_request', 'delete_records'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Important for ITSM and enterprise operations; change-management guardrails are mandatory.',
	},
	{
		id: 'snowflake',
		name: 'Snowflake',
		vendor: 'Snowflake',
		category: 'data_warehouse',
		priorityTier: 'P0',
		usefulnessScore0To100: 93,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct governed SQL/API access; restrict agents to read-only roles by default.',
		documentationPages: [
			{ label: 'Snowflake SQL API', url: 'https://docs.snowflake.com/en/developer-guide/sql-api/index', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Snowflake SQL API reference', url: 'https://docs.snowflake.com/en/developer-guide/sql-api/reference', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'key-pair auth', 'username/password', 'external browser/SSO'],
		coreAgentActions: ['query warehouse', 'generate reports', 'summarize data', 'create temporary tables', 'support analytics Q&A'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['write_or_delete_data', 'run_expensive_queries', 'change_roles', 'grant_permissions'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Create dedicated read-only roles and query budgets.',
	},
	{
		id: 'bigquery',
		name: 'BigQuery',
		vendor: 'Google Cloud',
		category: 'data_warehouse',
		priorityTier: 'P0',
		usefulnessScore0To100: 92,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'BigQuery API overview', url: 'https://cloud.google.com/bigquery/docs/reference/rest', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'BigQuery client libraries/API docs', url: 'https://cloud.google.com/bigquery/docs/reference/libraries', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'service account', 'workload identity'],
		coreAgentActions: ['query datasets', 'create reports', 'summarize metrics', 'export results', 'support analytics agents'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['modify_datasets', 'run_high_cost_queries', 'delete_tables', 'grant_iam'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use authorized views, row-level security, and cost controls.',
	},
	{
		id: 'postgresql',
		name: 'PostgreSQL',
		vendor: 'PostgreSQL Global Development Group',
		category: 'database',
		priorityTier: 'P0',
		usefulnessScore0To100: 90,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct database client through a controlled query gateway; default to read-only.',
		documentationPages: [
			{ label: 'PostgreSQL documentation', url: 'https://www.postgresql.org/docs/', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'PostgreSQL protocol docs', url: 'https://www.postgresql.org/docs/current/protocol.html', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['database username/password', 'SCRAM', 'Kerberos', 'certificates', 'cloud IAM depending on host'],
		coreAgentActions: ['query relational data', 'generate reports', 'insert/update records', 'explain schemas', 'support internal APIs'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['write_data', 'delete_data', 'alter_schema', 'grant_privileges'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Never expose arbitrary SQL writes without allowlists, timeouts, and transaction controls.',
	},
	{
		id: 'aws',
		name: 'Amazon Web Services',
		vendor: 'AWS',
		category: 'cloud_platform',
		priorityTier: 'P0',
		usefulnessScore0To100: 92,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct cloud SDKs through a policy-controlled execution layer; do not expose broad admin credentials to agents.',
		documentationPages: [
			{ label: 'AWS documentation', url: 'https://docs.aws.amazon.com/', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'AWS SDKs and tools', url: 'https://docs.aws.amazon.com/sdkref/latest/guide/overview.html', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['IAM roles', 'IAM users/access keys', 'STS AssumeRole', 'OIDC federation'],
		coreAgentActions: ['inspect resources', 'read logs/metrics', 'summarize costs', 'trigger runbooks', 'manage infrastructure after approval'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['create_or_delete_resources', 'change_iam', 'modify_security_groups', 'production_deployments'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Prefer read-only and diagnostic permissions first; use separate break-glass/change workflows.',
	},
	{
		id: 'okta',
		name: 'Okta',
		vendor: 'Okta',
		category: 'identity_access_management',
		priorityTier: 'P0',
		usefulnessScore0To100: 92,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct IAM APIs with strict allowlists and approval for any access-changing operation.',
		documentationPages: [
			{ label: 'Okta API docs', url: 'https://developer.okta.com/docs/api/', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Okta users API', url: 'https://developer.okta.com/docs/api/openapi/okta-management/management/tag/User/', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'API token'],
		coreAgentActions: ['look up users', 'manage groups', 'support access reviews', 'provision/deprovision after approval', 'audit identity state'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['deactivate_user', 'reset_mfa', 'change_group_membership', 'grant_admin_role'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Identity connectors require the strongest policy controls.',
	},
	{
		id: 'microsoft_entra_id',
		name: 'Microsoft Entra ID',
		vendor: 'Microsoft',
		category: 'identity_access_management',
		priorityTier: 'P0',
		usefulnessScore0To100: 92,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Microsoft Graph users API', url: 'https://learn.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Microsoft Graph groups API', url: 'https://learn.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0 via Microsoft Entra', 'delegated/application permissions'],
		coreAgentActions: ['look up users', 'manage groups', 'support access reviews', 'provision/deprovision', 'query directory state'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['change_group_membership', 'grant_roles', 'disable_user', 'reset_credentials'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use PIM/conditional access and separate approval for privileged changes.',
	},
	{
		id: 'stripe',
		name: 'Stripe',
		vendor: 'Stripe',
		category: 'payments_billing',
		priorityTier: 'P0',
		usefulnessScore0To100: 95,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct Stripe API with restricted keys for production payment workflows.',
		documentationPages: [
			{ label: 'Stripe API reference', url: 'https://docs.stripe.com/api', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Stripe APIs overview', url: 'https://docs.stripe.com/apis', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['secret API key', 'restricted API key', 'OAuth 2.0 for Connect'],
		coreAgentActions: ['look up customers', 'summarize invoices', 'create payment links', 'issue approved refunds', 'analyze subscriptions'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['refund_payment', 'create_charge', 'change_subscription', 'delete_customer', 'payout_or_transfer'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Payment and refund actions should require explicit user approval and audit logs.',
	},
	{
		id: 'shopify',
		name: 'Shopify',
		vendor: 'Shopify',
		category: 'commerce',
		priorityTier: 'P0',
		usefulnessScore0To100: 90,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Shopify GraphQL Admin API', url: 'https://shopify.dev/docs/api/admin-graphql', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Shopify REST Admin API', url: 'https://shopify.dev/docs/api/admin-rest', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'custom app access token'],
		coreAgentActions: ['look up orders', 'summarize inventory', 'draft product updates', 'manage customers', 'process fulfillment workflows'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['refund_order', 'cancel_order', 'change_inventory', 'publish_product_changes'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use approval gates for refunds, cancellations, and product publishing.',
	},
	{
		id: 'dropbox',
		name: 'Dropbox',
		vendor: 'Dropbox',
		category: 'file_storage',
		priorityTier: 'P1',
		usefulnessScore0To100: 85,
		implementationPattern: 'direct_api_or_connector_provider_tool',
		recommendedProviderStrategy: 'Use direct API for core workflows; use Composio/Pipedream/Zapier for long-tail actions.',
		documentationPages: [
			{ label: 'Dropbox HTTP API overview', url: 'https://www.dropbox.com/developers/documentation/http/overview', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Dropbox Business API', url: 'https://www.dropbox.com/developers/documentation/http/teams', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'team app scopes'],
		coreAgentActions: ['search files', 'download/upload files', 'create folders', 'summarize documents', 'manage links'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['share_files_externally', 'delete_files', 'team_admin_actions'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Use team-space permissions and scoped tokens.',
	},
	{
		id: 'custom_rest_openapi',
		name: 'Custom REST / OpenAPI APIs',
		vendor: 'Internal or third-party',
		category: 'custom_internal_systems',
		priorityTier: 'P0',
		usefulnessScore0To100: 96,
		implementationPattern: 'custom_mcp_or_tool_wrapper_over_openapi',
		recommendedProviderStrategy: 'Implement as MCP tools or typed function tools with strict schemas, allowlists, and policy checks.',
		documentationPages: [
			{ label: 'OpenAPI Specification', url: 'https://spec.openapis.org/oas/latest.html', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
			{ label: 'OpenAPI Initiative', url: 'https://www.openapis.org/', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'API keys', 'mTLS', 'service-to-service auth', 'custom auth'],
		coreAgentActions: ['call internal services', 'retrieve proprietary data', 'trigger workflows', 'wrap business operations as tools'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['any_state_changing_operation', 'payments', 'deletes', 'external_notifications', 'permission_changes'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Usually the highest-value connector family because it exposes proprietary business systems.',
	},
	{
		id: 'custom_graphql',
		name: 'Custom GraphQL APIs',
		vendor: 'Internal or third-party',
		category: 'custom_internal_systems',
		priorityTier: 'P1',
		usefulnessScore0To100: 84,
		implementationPattern: 'custom_mcp_or_tool_wrapper_over_graphql',
		recommendedProviderStrategy: 'Expose only selected queries/mutations; do not give agents broad arbitrary GraphQL access by default.',
		documentationPages: [
			{ label: 'GraphQL specification', url: 'https://spec.graphql.org/', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
			{ label: 'GraphQL official site', url: 'https://graphql.org/', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['OAuth 2.0', 'API keys', 'JWT', 'mTLS', 'custom auth'],
		coreAgentActions: ['query internal data', 'perform mutations', 'inspect schemas', 'build typed assistant tools'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['mutations', 'bulk_updates', 'permission_changes', 'delete_operations'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'GraphQL mutations should be converted into explicit, named, policy-checked tools.',
	},
	{
		id: 'sql_gateway',
		name: 'Controlled SQL Gateway',
		vendor: 'Internal',
		category: 'custom_data_access',
		priorityTier: 'P0',
		usefulnessScore0To100: 90,
		implementationPattern: 'controlled_query_gateway_with_read_only_roles',
		recommendedProviderStrategy: 'Build a query gateway with read-only roles, query allowlists, timeouts, row limits, and cost controls.',
		documentationPages: [
			{ label: 'PostgreSQL docs as example SQL backend', url: 'https://www.postgresql.org/docs/', status: DOC_STATUS, type: 'official_docs' },
			{ label: 'Snowflake SQL API as example governed SQL API', url: 'https://docs.snowflake.com/en/developer-guide/sql-api/index', status: DOC_STATUS, type: 'official_docs' },
		],
		authModels: ['database roles', 'OIDC/IAM', 'service account', 'query gateway tokens'],
		coreAgentActions: ['answer business questions', 'generate governed reports', 'run approved queries', 'summarize database schemas'],
		writeRisk: 'critical',
		humanApprovalRequiredFor: ['write_queries', 'schema_changes', 'unbounded_queries', 'sensitive_data_export'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Prefer semantic-layer queries or generated SQL review for regulated data.',
	},
	{
		id: 'webhooks',
		name: 'Webhooks',
		vendor: 'Internal or third-party',
		category: 'eventing_workflow',
		priorityTier: 'P1',
		usefulnessScore0To100: 82,
		implementationPattern: 'event_trigger_into_agent_or_workflow_orchestrator',
		recommendedProviderStrategy: 'Use signed events, replay protection, idempotency keys, and event allowlists.',
		documentationPages: [
			{ label: 'GitHub webhooks example', url: 'https://docs.github.com/en/webhooks', status: DOC_STATUS_UNVERIFIED, type: 'official_docs' },
		],
		authModels: ['HMAC signatures', 'shared secret', 'mTLS', 'OAuth-backed event subscriptions'],
		coreAgentActions: ['receive events', 'trigger workflows', 'notify agents', 'start background processing', 'sync external state'],
		writeRisk: 'high',
		humanApprovalRequiredFor: ['trigger_destructive_workflow', 'external_notifications', 'payment_or_access_workflows'],
		recommendedInitialMode: 'read_only_then_draft_write_actions',
		notes: 'Validate webhook signatures and guard against replay attacks.',
	},
] as const satisfies readonly DirectConnectorCatalogEntry[];

export type DirectConnectorCatalogId = (typeof DIRECT_CONNECTOR_CATALOG)[number]['id'];

export const CONNECTOR_CATALOG_METADATA = {
	title: 'Agentic AI Assistant Connector Catalog',
	schemaVersion: '1.0',
	generatedDate: '2026-05-19',
	timezoneContext: 'Europe/Rome',
	scope: 'Curated production-oriented catalog of useful direct connectors for an agentic AI assistant.',
	recommendedArchitecture: 'MCP + direct strategic connectors + permission-aware enterprise search/RAG.',
} as const;

export const CONNECTOR_IMPLEMENTATION_CONTROLS = {
	globalDefaults: [
		'Start every connector in read-only mode where possible.',
		'Expose write operations only as narrowly scoped tools with typed schemas.',
		'Use OAuth or service accounts with least privilege; avoid shared user credentials.',
		'Preserve source-system permissions in retrieval and search flows.',
		'Require human approval for destructive, external-facing, financial, legal, HR, identity, production, and security actions.',
		'Log every tool call with user, connector, input, output summary, approval status, and resulting external record IDs.',
		'Add rate limits, retries, idempotency keys, and loop-detection safeguards.',
		'Treat content from email, chat, docs, tickets, and websites as untrusted input to mitigate prompt injection.',
	],
	recommendedV1ConnectorGroups: [
		'Google Workspace or Microsoft 365',
		'Slack or Microsoft Teams',
		'GitHub or GitLab',
		'Jira/Confluence or Linear/Notion',
		'Salesforce or HubSpot',
		'Zendesk/Intercom/ServiceNow',
		'Snowflake/BigQuery/Databricks/PostgreSQL',
		'Okta or Microsoft Entra ID',
		'Stripe/Shopify/QuickBooks/NetSuite depending on business model',
		'Custom REST/OpenAPI, GraphQL, SQL gateway, and webhook connectors',
	],
} as const;

const DIRECT_CONNECTOR_BY_ID = new Map<string, DirectConnectorCatalogEntry>(
	DIRECT_CONNECTOR_CATALOG.map((connector) => [connector.id, connector])
);

export const CONNECTOR_CATALOG_COUNTS = {
	directConnectors: DIRECT_CONNECTOR_CATALOG.length,
	totalCatalogEntries: DIRECT_CONNECTOR_CATALOG.length,
} as const;

export function getDirectConnectorCatalogItem(id: string): DirectConnectorCatalogEntry | undefined {
	return DIRECT_CONNECTOR_BY_ID.get(id);
}

export function isDirectConnectorCatalogId(value: string): value is DirectConnectorCatalogId {
	return DIRECT_CONNECTOR_BY_ID.has(value);
}

export function listDirectConnectorsByPriority(
	priorityTier: ConnectorPriorityTier
): DirectConnectorCatalogEntry[] {
	return DIRECT_CONNECTOR_CATALOG.filter((connector) => connector.priorityTier === priorityTier);
}

export const OPENAI_CONNECTOR_CATALOG = [
	{
		id: 'connector_dropbox',
		directConnectorId: 'dropbox',
		name: 'Dropbox',
		description: 'Search and fetch files from Dropbox.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_dropbox.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_dropbox.providerDocsLabel,
		environmentSecretNames: ['DROPBOX_CLIENT_ID', 'DROPBOX_CLIENT_SECRET', 'DROPBOX_ACCESS_TOKEN'],
		platformDocumentationPages: [
			{ label: 'Dropbox HTTP API', url: 'https://www.dropbox.com/developers/documentation/http/overview' },
			{ label: 'Dropbox OAuth guide', url: 'https://developers.dropbox.com/oauth-guide' },
		],
		example: { tool: 'search_files', input: { query: 'quarterly report' } },
		tools: ['search', 'fetch', 'search_files', 'fetch_file', 'list_recent_files', 'get_profile'],
		scopes: ['files.metadata.read', 'files.content.read', 'account_info.read'],
		setupUrl: 'https://www.dropbox.com/developers/apps',
		setupInstructions: [
			'Go to the Dropbox App Console and create or open an app.',
			'Enable the listed file and account scopes for the app.',
			'Complete OAuth for your account and paste the resulting access token here.',
		],
	},
	{
		id: 'connector_gmail',
		directConnectorId: 'gmail',
		name: 'Gmail',
		description: 'Search, read, draft, send, and manage Gmail messages.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_gmail.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_gmail.providerDocsLabel,
		environmentSecretNames: ['GOOGLE_OAUTH_CLIENT_ID', 'GOOGLE_OAUTH_CLIENT_SECRET'],
		platformDocumentationPages: [
			{ label: 'Gmail API guides', url: 'https://developers.google.com/workspace/gmail/api/guides' },
			{ label: 'Gmail API reference', url: 'https://developers.google.com/workspace/gmail/api/reference/rest' },
		],
		example: { tool: 'search_emails', input: { query: 'from:alice@example.com newer_than:7d' } },
		tools: [
			'get_profile',
			'search_emails',
			'search_email_ids',
			'get_recent_emails',
			'read_email',
			'batch_read_email',
			'create_draft',
			'send_email',
			'trash_email',
		],
		scopes: [
			'https://www.googleapis.com/auth/userinfo.email',
			'https://www.googleapis.com/auth/userinfo.profile',
			'https://www.googleapis.com/auth/gmail.readonly',
			'https://www.googleapis.com/auth/gmail.compose',
			'https://www.googleapis.com/auth/gmail.send',
			'https://www.googleapis.com/auth/gmail.modify',
		],
		authKind: 'mcp_env',
		redirectUri: 'http://127.0.0.1:<temporary-port>',
		setupUrl: 'https://console.cloud.google.com/apis/credentials',
		setupInstructions: [
			'Go to Google Cloud Console, enable the Gmail API, and configure the OAuth consent screen.',
			'Create an OAuth client with application type Desktop app.',
			'Set GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET in the app environment before launching Friday.',
			'Save the connector, then use Connect to finish Google consent.',
		],
	},
	{
		id: 'connector_googlecalendar',
		directConnectorId: 'google_calendar',
		name: 'Google Calendar',
		description: 'Search, read, create, update, and delete Google Calendar events.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_googlecalendar.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_googlecalendar.providerDocsLabel,
		environmentSecretNames: ['GOOGLE_OAUTH_CLIENT_ID', 'GOOGLE_OAUTH_CLIENT_SECRET'],
		platformDocumentationPages: [
			{ label: 'Google Calendar API overview', url: 'https://developers.google.com/workspace/calendar/api/guides/overview' },
			{ label: 'Calendar API reference', url: 'https://developers.google.com/workspace/calendar/api/v3/reference' },
		],
		example: { tool: 'search_events', input: { query: 'planning', calendarId: 'primary' } },
		tools: [
			'get_profile',
			'list_calendars',
			'search',
			'fetch',
			'search_events',
			'read_event',
			'create_event',
			'update_event',
			'delete_event',
		],
		scopes: [
			'https://www.googleapis.com/auth/userinfo.email',
			'https://www.googleapis.com/auth/userinfo.profile',
			'https://www.googleapis.com/auth/calendar.readonly',
			'https://www.googleapis.com/auth/calendar.events.readonly',
			'https://www.googleapis.com/auth/calendar.events',
		],
		authKind: 'mcp_env',
		redirectUri: 'http://127.0.0.1:<temporary-port>',
		setupUrl: 'https://console.cloud.google.com/apis/credentials',
		setupInstructions: [
			'Go to Google Cloud Console, enable the Google Calendar API, and configure the OAuth consent screen.',
			'Create an OAuth client with application type Desktop app.',
			'Set GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET in the app environment before launching Friday.',
			'Save the connector, then use Connect to finish Google consent.',
		],
	},
	{
		id: 'connector_googledrive',
		directConnectorId: 'google_drive',
		name: 'Google Drive',
		description: 'Search, read, create, and inspect Google Drive files.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_googledrive.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_googledrive.providerDocsLabel,
		environmentSecretNames: ['GOOGLE_OAUTH_CLIENT_ID', 'GOOGLE_OAUTH_CLIENT_SECRET'],
		platformDocumentationPages: [
			{ label: 'Google Drive API overview', url: 'https://developers.google.com/workspace/drive/api/guides/about-sdk' },
			{ label: 'Drive API reference', url: 'https://developers.google.com/drive/api/reference/rest/v3' },
		],
		example: { tool: 'search_files', input: { query: "name contains 'proposal'" } },
		tools: [
			'get_profile',
			'search_files',
			'list_recent_files',
			'read_file_content',
			'get_file_metadata',
			'get_file_permissions',
			'download_file_content',
			'create_file',
			'list_drives',
			'search',
			'recent_documents',
			'fetch',
		],
		scopes: [
			'https://www.googleapis.com/auth/userinfo.email',
			'https://www.googleapis.com/auth/userinfo.profile',
			'https://www.googleapis.com/auth/drive.readonly',
			'https://www.googleapis.com/auth/drive.file',
		],
		authKind: 'mcp_env',
		redirectUri: 'http://127.0.0.1:<temporary-port>',
		setupUrl: 'https://console.cloud.google.com/apis/credentials',
		setupInstructions: [
			'Go to Google Cloud Console, enable the Google Drive API, and configure the OAuth consent screen with Drive readonly and Drive file scopes.',
			'Create an OAuth client with application type Desktop app.',
			'Set GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET in the app environment before launching Friday.',
			'Save the connector, then use Connect to finish Google consent.',
		],
	},
	{
		id: 'connector_microsoftteams',
		directConnectorId: 'microsoft_teams',
		name: 'Microsoft Teams',
		description: 'Search Teams chats and channel messages.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_microsoftteams.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_microsoftteams.providerDocsLabel,
		environmentSecretNames: [
			'MICROSOFT_TENANT_ID',
			'MICROSOFT_CLIENT_ID',
			'MICROSOFT_CLIENT_SECRET',
			'MICROSOFT_TEAMS_ACCESS_TOKEN',
		],
		platformDocumentationPages: [
			{ label: 'Microsoft Teams Graph overview', url: 'https://learn.microsoft.com/en-us/graph/teams-concept-overview' },
			{ label: 'Teams API reference', url: 'https://learn.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0' },
		],
		example: { tool: 'search', input: { query: 'deployment incident' } },
		tools: ['search', 'fetch', 'get_chat_members', 'get_profile'],
		scopes: ['Chat.Read', 'ChannelMessage.Read.All', 'User.Read'],
		setupUrl: 'https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade',
		setupInstructions: [
			'Go to Microsoft Entra admin center > App registrations.',
			'Create or open an app registration and grant the listed Microsoft Graph permissions.',
			'Complete OAuth for the tenant/user and paste the resulting access token here.',
		],
	},
	{
		id: 'connector_outlookcalendar',
		directConnectorId: 'outlook',
		name: 'Outlook Calendar',
		description: 'Search and read Outlook Calendar events.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_outlookcalendar.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_outlookcalendar.providerDocsLabel,
		environmentSecretNames: [
			'MICROSOFT_TENANT_ID',
			'MICROSOFT_CLIENT_ID',
			'MICROSOFT_CLIENT_SECRET',
			'MICROSOFT_OUTLOOK_CALENDAR_ACCESS_TOKEN',
		],
		platformDocumentationPages: [
			{ label: 'Outlook calendar API overview', url: 'https://learn.microsoft.com/en-us/graph/outlook-calendar-concept-overview' },
			{ label: 'Microsoft Graph auth concepts', url: 'https://learn.microsoft.com/en-us/graph/auth/auth-concepts' },
		],
		example: { tool: 'list_events', input: { calendarId: 'primary' } },
		tools: ['search_events', 'fetch_event', 'fetch_events_batch', 'list_events', 'get_profile'],
		scopes: ['Calendars.Read', 'User.Read'],
		setupUrl: 'https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade',
		setupInstructions: [
			'Go to Microsoft Entra admin center > App registrations.',
			'Create or open an app registration and grant the listed Microsoft Graph calendar scopes.',
			'Complete OAuth for the account and paste the resulting access token here.',
		],
	},
	{
		id: 'connector_outlookemail',
		directConnectorId: 'outlook',
		name: 'Outlook Email',
		description: 'Search and read Outlook email messages.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_outlookemail.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_outlookemail.providerDocsLabel,
		environmentSecretNames: [
			'MICROSOFT_TENANT_ID',
			'MICROSOFT_CLIENT_ID',
			'MICROSOFT_CLIENT_SECRET',
			'MICROSOFT_OUTLOOK_EMAIL_ACCESS_TOKEN',
		],
		platformDocumentationPages: [
			{ label: 'Outlook mail API overview', url: 'https://learn.microsoft.com/en-us/graph/outlook-mail-concept-overview' },
			{ label: 'Microsoft Graph auth concepts', url: 'https://learn.microsoft.com/en-us/graph/auth/auth-concepts' },
		],
		example: { tool: 'search_messages', input: { query: 'invoice hasAttachments:true' } },
		tools: [
			'get_profile',
			'list_messages',
			'search_messages',
			'get_recent_emails',
			'fetch_message',
			'fetch_messages_batch',
		],
		scopes: ['User.Read', 'Mail.Read'],
		setupUrl: 'https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade',
		setupInstructions: [
			'Go to Microsoft Entra admin center > App registrations.',
			'Create or open an app registration and grant the listed Microsoft Graph mail scopes.',
			'Complete OAuth for the mailbox account and paste the resulting access token here.',
		],
	},
	{
		id: 'connector_sharepoint',
		directConnectorId: 'sharepoint_onedrive',
		name: 'SharePoint',
		description: 'Search and fetch SharePoint and OneDrive documents.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_sharepoint.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_sharepoint.providerDocsLabel,
		environmentSecretNames: [
			'MICROSOFT_TENANT_ID',
			'MICROSOFT_CLIENT_ID',
			'MICROSOFT_CLIENT_SECRET',
			'MICROSOFT_SHAREPOINT_ACCESS_TOKEN',
		],
		platformDocumentationPages: [
			{ label: 'OneDrive files in Microsoft Graph', url: 'https://learn.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0' },
			{ label: 'SharePoint sites API', url: 'https://learn.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0' },
		],
		example: { tool: 'fetch', input: { id: 'drive-item-id' } },
		tools: ['get_site', 'search', 'list_recent_documents', 'fetch', 'get_profile'],
		scopes: ['Sites.Read.All', 'Files.Read.All', 'User.Read'],
		setupUrl: 'https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade',
		setupInstructions: [
			'Go to Microsoft Entra admin center > App registrations.',
			'Create or open an app registration and grant the listed Microsoft Graph files and sites scopes.',
			'Complete OAuth for the account and paste the resulting access token here.',
		],
	},

	{
		id: 'connector_remote_mcp',
		directConnectorId: 'custom_rest_openapi',
		name: 'Remote MCP Server',
		description: 'Connect to any remote MCP server over streamable HTTP and discover its tools dynamically.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_remote_mcp.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_remote_mcp.providerDocsLabel,
		environmentSecretNames: ['REMOTE_MCP_API_KEY'],
		platformDocumentationPages: [
			{ label: 'Build an MCP client', url: 'https://modelcontextprotocol.io/docs/develop/build-client' },
		],
		example: { tool: 'discovered_tool', input: {} },
		tools: [],
		scopes: [],
		setupUrl: 'https://modelcontextprotocol.io/docs/develop/build-client',
		setupInstructions: [
			'Run or choose a remote MCP server that exposes the target service tools.',
			'Store any required API key in an environment variable, then reference that variable in the connector MCP auth config.',
			'Save the connector and refresh tools to discover the server capabilities.',
		],
		authKind: 'mcp_env',
		runtimeKind: 'mcp',
		allowMultipleInstances: true,
	},
	{
		id: 'connector_stdio_mcp',
		directConnectorId: 'custom_rest_openapi',
		name: 'Local MCP Server',
		description: 'Launch a local MCP server over stdio and discover its tools dynamically.',
		docsPath: PROVIDER_CONNECTOR_DOCS.connector_stdio_mcp.providerDocsPath,
		docsLabel: PROVIDER_CONNECTOR_DOCS.connector_stdio_mcp.providerDocsLabel,
		environmentSecretNames: [],
		platformDocumentationPages: [
			{ label: 'Build an MCP client', url: 'https://modelcontextprotocol.io/docs/develop/build-client' },
		],
		example: { tool: 'discovered_tool', input: {} },
		tools: [],
		scopes: [],
		setupUrl: 'https://modelcontextprotocol.io/docs/develop/build-client',
		setupInstructions: [
			'Install or build a local MCP server package.',
			'Configure the command, args, and any env var mappings needed by the server.',
			'Save the connector and refresh tools to discover the server capabilities.',
		],
		authKind: 'mcp_env',
		runtimeKind: 'mcp',
		allowMultipleInstances: true,
	},
] as const satisfies readonly OpenAiConnectorCatalogEntry[];

export type OpenAiConnectorId = (typeof OPENAI_CONNECTOR_CATALOG)[number]['id'];

export function getConnectorCatalogItem(id: OpenAiConnectorId) {
	return OPENAI_CONNECTOR_CATALOG.find((connector) => connector.id === id);
}

export const PLUGGABLE_MCP_CONNECTOR_IDS = [
	'connector_remote_mcp',
	'connector_stdio_mcp',
] as const satisfies readonly OpenAiConnectorId[];

export function getConnectorAuthKind(id: OpenAiConnectorId): ConnectorAuthKind {
	return getConnectorCatalogItem(id)?.authKind ?? 'mcp_env';
}

export function connectorAllowsMultipleInstances(id: OpenAiConnectorId): boolean {
	return getConnectorCatalogItem(id)?.allowMultipleInstances ?? true;
}

export function isOpenAiConnectorId(value: string): value is OpenAiConnectorId {
	return OPENAI_CONNECTOR_CATALOG.some((connector) => connector.id === value);
}
