export declare const GMAIL_CONNECTOR: {
    readonly id: "gmail";
    readonly connectorId: "connector_gmail";
    readonly name: "Gmail";
    readonly url: "https://gmailmcp.googleapis.com/mcp/v1";
    readonly description: "Read and search Gmail messages.";
    readonly iconId: "gmail";
    readonly requireApproval: "always";
    readonly deferLoading: false;
    readonly enabled: true;
    readonly oauth: {
        readonly service: "google";
        readonly serviceId: "gmail";
        readonly clientIdEnv: "GOOGLE_OAUTH_CLIENT_ID";
        readonly clientSecretEnv: "GOOGLE_OAUTH_CLIENT_SECRET";
        readonly authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth";
        readonly tokenUrl: "https://oauth2.googleapis.com/token";
        readonly userInfoUrl: "https://openidconnect.googleapis.com/v1/userinfo";
        readonly scopes: readonly ["openid", "email", "profile", "https://www.googleapis.com/auth/gmail.modify"];
        readonly accessType: "offline";
        readonly prompt: "consent";
    };
};
export declare const CALENDAR_CONNECTOR: {
    readonly id: "calendar";
    readonly connectorId: "connector_googlecalendar";
    readonly name: "Calendar";
    readonly url: "https://www.googleapis.com/calendar/v3";
    readonly description: "Read and search calendar events.";
    readonly iconId: "google_calendar";
    readonly requireApproval: "always";
    readonly deferLoading: false;
    readonly enabled: true;
    readonly oauth: {
        readonly service: "google";
        readonly serviceId: "calendar";
        readonly clientIdEnv: "GOOGLE_OAUTH_CLIENT_ID";
        readonly clientSecretEnv: "GOOGLE_OAUTH_CLIENT_SECRET";
        readonly authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth";
        readonly tokenUrl: "https://oauth2.googleapis.com/token";
        readonly userInfoUrl: "https://openidconnect.googleapis.com/v1/userinfo";
        readonly scopes: readonly ["openid", "email", "profile", "https://www.googleapis.com/auth/calendar.readonly", "https://www.googleapis.com/auth/calendar.events.readonly"];
        readonly accessType: "offline";
        readonly prompt: "consent";
    };
};
export declare const CONNECTOR_DEFAULTS: readonly [{
    readonly id: "gmail";
    readonly connectorId: "connector_gmail";
    readonly name: "Gmail";
    readonly url: "https://gmailmcp.googleapis.com/mcp/v1";
    readonly description: "Read and search Gmail messages.";
    readonly iconId: "gmail";
    readonly requireApproval: "always";
    readonly deferLoading: false;
    readonly enabled: true;
    readonly oauth: {
        readonly service: "google";
        readonly serviceId: "gmail";
        readonly clientIdEnv: "GOOGLE_OAUTH_CLIENT_ID";
        readonly clientSecretEnv: "GOOGLE_OAUTH_CLIENT_SECRET";
        readonly authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth";
        readonly tokenUrl: "https://oauth2.googleapis.com/token";
        readonly userInfoUrl: "https://openidconnect.googleapis.com/v1/userinfo";
        readonly scopes: readonly ["openid", "email", "profile", "https://www.googleapis.com/auth/gmail.modify"];
        readonly accessType: "offline";
        readonly prompt: "consent";
    };
}, {
    readonly id: "calendar";
    readonly connectorId: "connector_googlecalendar";
    readonly name: "Calendar";
    readonly url: "https://www.googleapis.com/calendar/v3";
    readonly description: "Read and search calendar events.";
    readonly iconId: "google_calendar";
    readonly requireApproval: "always";
    readonly deferLoading: false;
    readonly enabled: true;
    readonly oauth: {
        readonly service: "google";
        readonly serviceId: "calendar";
        readonly clientIdEnv: "GOOGLE_OAUTH_CLIENT_ID";
        readonly clientSecretEnv: "GOOGLE_OAUTH_CLIENT_SECRET";
        readonly authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth";
        readonly tokenUrl: "https://oauth2.googleapis.com/token";
        readonly userInfoUrl: "https://openidconnect.googleapis.com/v1/userinfo";
        readonly scopes: readonly ["openid", "email", "profile", "https://www.googleapis.com/auth/calendar.readonly", "https://www.googleapis.com/auth/calendar.events.readonly"];
        readonly accessType: "offline";
        readonly prompt: "consent";
    };
}];
