export const GMAIL_CONNECTOR = {
    id: 'gmail',
    connectorId: 'connector_gmail',
    name: 'Gmail',
    url: 'https://gmailmcp.googleapis.com/mcp/v1',
    description: 'Read and search Gmail messages.',
    iconId: 'gmail',
    requireApproval: 'always',
    deferLoading: false,
    enabled: true,
    oauth: {
        service: 'google',
        serviceId: 'gmail',
        clientIdEnv: 'GOOGLE_OAUTH_CLIENT_ID',
        clientSecretEnv: 'GOOGLE_OAUTH_CLIENT_SECRET',
        authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        userInfoUrl: 'https://openidconnect.googleapis.com/v1/userinfo',
        scopes: ['openid', 'email', 'profile', 'https://www.googleapis.com/auth/gmail.modify'],
        accessType: 'offline',
        prompt: 'consent',
    },
};
export const CALENDAR_CONNECTOR = {
    id: 'calendar',
    connectorId: 'connector_googlecalendar',
    name: 'Calendar',
    url: 'https://www.googleapis.com/calendar/v3',
    description: 'Read and search calendar events.',
    iconId: 'google_calendar',
    requireApproval: 'always',
    deferLoading: false,
    enabled: true,
    oauth: {
        service: 'google',
        serviceId: 'calendar',
        clientIdEnv: 'GOOGLE_OAUTH_CLIENT_ID',
        clientSecretEnv: 'GOOGLE_OAUTH_CLIENT_SECRET',
        authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        userInfoUrl: 'https://openidconnect.googleapis.com/v1/userinfo',
        scopes: [
            'openid',
            'email',
            'profile',
            'https://www.googleapis.com/auth/calendar.readonly',
            'https://www.googleapis.com/auth/calendar.events.readonly',
        ],
        accessType: 'offline',
        prompt: 'consent',
    },
};
export const CONNECTOR_DEFAULTS = [GMAIL_CONNECTOR, CALENDAR_CONNECTOR];
