const TOOL_ALIASES: Readonly<Record<string, string>> = {
	create_schedule: 'create_task',
	delete_schedule: 'delete_task',
	edit: 'edit_file',
	exec: 'exec_command',
	web_browser: 'use_web_browser',
	web_fetch: 'fetch_web_page',
	web_search: 'search_web',
	get_schedule: 'get_task',
	health_check_settings_update: 'update_health_cheeck_settings',
	health_check_update: 'update_health_cheeck',
	health_settings_update: 'update_health_cheeck_settings',
	health_update: 'update_health_cheeck',
	knowledge_query: 'query_knowledge',
	knowledge_search: 'search_knowledge',
	memory_forget: 'forget_memory',
	memory_list: 'list_memories',
	memory_save: 'save_memory',
	list_schedules: 'list_tasks',
	pause_schedule: 'pause_task',
	recorder_camera: 'camera_recorder',
	recorder_camera_status: 'camera_recorder_status',
	recorder_camera_stop: 'camera_recorder_stop',
	recorder_microphone: 'microphone_recorder',
	recorder_microphone_status: 'microphone_recorder_status',
	recorder_microphone_stop: 'microphone_recorder_stop',
	recorder_screen: 'screen_recorder',
	recorder_screen_status: 'screen_recorder_status',
	recorder_screen_stop: 'screen_recorder_stop',
	read: 'read_file',
	resume_schedule: 'resume_task',
	run_schedule_now: 'run_task_now',
	update_schedule: 'update_task',
	wiki_get_recent_activity: 'get_recent_wiki_activity',
	wiki_ingest_source: 'ingest_wiki_source',
	wiki_lint: 'lint_wiki',
	wiki_query: 'query_wiki',
	wiki_read_page: 'read_wiki_page',
	wiki_rebuild_index: 'rebuild_wiki_index',
	wiki_review_changes: 'review_wiki_changes',
	wiki_save_analysis: 'save_wiki_analysis',
	wiki_search: 'search_wiki',
	write: 'write_file',
};

export function currentToolName(name: string): string {
	return TOOL_ALIASES[name] ?? name;
}
